### PR TITLE
Fix classname resolution syntax

### PR DESCRIPTION
**Pull request by corneliusio**

### CODE REVIEW

**Comment by croxton** [comment]
Presumably this is so it works in PHP 7.x ?

**Comment by corneliusio** [comment]
@croxton Yeah, guess I didn't check what the min version the existing syntax worked with, but I did see that it had been updated in pretty much every other newer branch and I was working on some updates for a very old legacy site we have setting around and ran into this issue and unfortunately it is running on php@7.4.

**Comment by croxton** [comment]
Makes sense, Craft 3 is meant to support 7.x so this version of Imgixer should too. I guess.

**Comment by croxton** [comment]
Thanks for the catch!

**Pull request merged**
